# Setup
title:               Weidumller Evt
tagline:             'Report Site'
description:         'This website show the past EVT report about weidumller app on Android and Ios devices.'
url:                 http://kuanchunchen.github.io/WM_Evt_Site
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Willy Chen
  url:               https://www.linkedin.com/in/kuan-chun-chen-3b703216b/
  email:             championsheeps@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
