# Setup
title:               Weidumller Evt
tagline:             'Report Site'
description:         'This website show the past EVT report about weidumller app on Android and Ios devices.'
url:                 https://kuanchunchen.github.io/WM_Evt_Site/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
