# Site settings
name: Weidumller Evt Report Site

url: https://kuanchunchen.github.io/WM_Evt_Site/

baseurl: ''


#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']


# About/contact
author:
  name:              Willy Chen
  url:               https://www.linkedin.com/in/kuan-chun-chen-3b703216b/
  email:             championsheeps@gmail.com

# Custom vars
version:             1.2.0
google_analytics_id: G-1MP4FL6EY3

# Custom description

description: Both android and ios evt report can see here !
meta_description: evt;android;ios;kotlin;wiilyChen;eleg.aces.kc;
motto: Weidumller Evt Report Site
banner: Get the evt report which you would like to see !